### ISSUE TITLE
Product Sync crashing on categoryOrderHints

### ISSUE THREAD

**Issue by valtechtmn** [commercetools/commercetools-sync-java#1130]
Before anything let me say that I'm very new to using this repo, please do let me know if I'm doing something completly wrong.

**Describe the bug**
When attempting to sync a product between two commercetools environment we end up with this error :
```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.spi.FailsafeFuture.completeResult(FailsafeFuture.java:99)
	at dev.failsafe.AsyncExecutionImpl.complete(AsyncExecutionImpl.java:153)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$handleAsync$5(RetryPolicyExecutor.java:155)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2257)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$handleAsync$6(RetryPolicyExecutor.java:150)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.Functions.lambda$toAsync$5(Functions.java:202)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.Functions.lambda$getPromiseOfStage$2(Functions.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.spi.FailsafeFuture.completeResult(FailsafeFuture.java:99)
	at dev.failsafe.AsyncExecutionImpl.complete(AsyncExecutionImpl.java:153)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$handleAsync$5(RetryPolicyExecutor.java:155)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2257)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$handleAsync$6(RetryPolicyExecutor.java:150)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.Functions.lambda$toAsync$5(Functions.java:202)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
	at dev.failsafe.Functions.lambda$getPromiseOfStage$2(Functions.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.commercetools.sync.products.utils.ProductReferenceResolutionUtils.lambda$mapToCategoryReferencePair$7(ProductReferenceResolutionUtils.java:266)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.commercetools.sync.products.utils.ProductReferenceResolutionUtils.mapToCategoryReferencePair(ProductReferenceResolutionUtils.java:258)
	at com.commercetools.sync.products.utils.ProductReferenceResolutionUtils.lambda$mapToProductDrafts$3(ProductReferenceResolutionUtils.java:135)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.commercetools.sync.products.utils.ProductReferenceResolutionUtils.mapToProductDrafts(ProductReferenceResolutionUtils.java:175)
	at com.commercetools.sync.products.utils.ProductTransformUtils$ProductTransformServiceImpl.lambda$transformReferencesAndMapToProductDrafts$3(ProductTransformUtils.java:117)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 60 more
```

**To Reproduce**
Have a product in the source environment with empty categoryOrderHints, json representation from CT HTTP API should look like this :
`"categoryOrderHints": {},`

Query all products just like in the doc example using :
```
final ByProjectKeyProductProjectionsGet byProjectKeyProductsGet = apiRootForStage.productProjections().get().addStaged(true);

final List<ProductProjection> products = QueryUtils.queryAll(byProjectKeyProductsGet,
                (productProjections) -> productProjections)
        .thenApply(lists -> lists.stream().flatMap(List::stream).collect(Collectors.toList()))
        .toCompletableFuture()
        .join();
```

This results in the product categoryOrderHints modelization being :
`CategoryOrderHintsImpl[values=<null>]`

Then attempt to transform the product projections to product draft using once again the example code :
```
final List<ProductDraft> productDrafts = ProductTransformUtils.toProductDrafts(apiRootForStage, referenceIdToKeyCache, products).join();
```

The result is the above exception is thrown logically at ProductReferenceResolutionUtils.mapToCategoryReferencePair#102 :
```
String categoryOrderHintValue = (String)categoryOrderHints.values().get(categoryId);
```

It looks like either something is weird with our products or with the serialization. The mapToCategoryReferencePair method is checking for orderHints being null entirely but doesn't account for it having the values property as null.

For now we have brute forced and just set all categoryOrderHints to null when values was null and then the sync works perfectly.
Let me know what you think.

**Comment by dfrommi** [comment]
Should be fixed by this one: https://github.com/commercetools/commercetools-sync-java/pull/1126

I've experienced the same, and my PR should fix it. Just waiting for feedback and merge there.

**Comment by valtechtmn** [comment]
Yeah that should do it, thanks for your work !
I will be eagerly awaiting the new build with this fix in.

**Comment by lojzatran** [comment]
The fix is already released: https://github.com/commercetools/commercetools-sync-java/releases/tag/10.0.3

@valtechtmn please check and if there are problems, you can reopen this issue.

@dfrommi thank you for your contribution.
