### ISSUE TITLE
ClassCastException while getting response

### ISSUE THREAD

**Issue by jarzynp** [commercetools/commercetools-sync-java#466]
**Describe the bug**
While doing ProductType synchronization following error appeared in our logs: 
```
java.util.concurrent.CompletionException: java.lang.ClassCastException: java.util.concurrent.CompletionException cannot be cast to com.commercetools.sync.commons.exceptions.ReferenceResolutionException
```

Bug exists in this line: https://github.com/commercetools/commercetools-sync-java/blob/d0b2a9877b5e45b025ba370de05de100a89eaa0a/src/main/java/com/commercetools/sync/producttypes/ProductTypeSync.java#L234

**To Reproduce**
Unfortunately we don't have any details what was the cause of it and don't know how to reproduce.

**Expected behavior**
More detailed exception about what actually happened (maybe exception could contain response?).

**Additional context**
Stacktrace:
```
java.util.concurrent.CompletionException: java.lang.ClassCastException: java.util.concurrent.CompletionException cannot be cast to com.commercetools.sync.commons.exceptions.ReferenceResolutionException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
	at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884)
	at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196)
	at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:110)
	at com.commercetools.sync.producttypes.ProductTypeSync.lambda$syncBatch$7(ProductTypeSync.java:233)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.commercetools.sync.producttypes.ProductTypeSync.syncBatch(ProductTypeSync.java:244)
	at com.commercetools.sync.producttypes.ProductTypeSync.lambda$null$1(ProductTypeSync.java:172)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.commercetools.sync.sphere.UpdateActionRetrySupervisorImpl.lambda$supervise$0(UpdateActionRetrySupervisorImpl.java:63)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.util.concurrent.CompletionException cannot be cast to com.commercetools.sync.commons.exceptions.ReferenceResolutionException
	at com.commercetools.sync.producttypes.ProductTypeSync.lambda$null$6(ProductTypeSync.java:235)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	... 23 common frames omitted```

**Comment by butenkor** [comment]
Thanks for reporting this. It seems that we might get here also into network-related exceptions like `io.sphere.sdk.http.HttpException`. In your example, `CompletionException` does not seem to be the exception root cause. 

Options to evaluate: 
- pass an exception to `handleError` without casting right away (requires that error context Infos like `FAILED_TO_RESOLVE_REFERENCES` is added by the callee)

- add instanceof check for type ReferenceResolutionExceptions

**Comment by butenkor** [comment]
Another example:

```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.ClassCastException: io.sphere.sdk.http.HttpException cannot be cast to com.commercetools.sync.commons.exceptions.ReferenceResolutionException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:888)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at 
```

**Comment by ahmetoz** [comment]
Release [1.8.2](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#182----april-30-2020)
