### ISSUE TITLE
Unresolved References lacking full support for products' keys

### ISSUE THREAD

**Issue by svaj** [commercetools/commercetools-sync-java#474]
**Describe the bug**
UnresolvedReferencesService cannot handle product keys that do not adhere to the regex ` [-_~.a-zA-Z0-9]+.`

**To Reproduce**
1. Create a product with the following, valid, key `Get a $100 Visa® Reward Card because you’re ordering TV`
2. Reference another product in an attribute of the above product.
3. Delete the referenced product
4. (using the project sync tool)  run a product sync
5. See error

> [Thread-11] ERROR com.commercetools.project.sync.CliRunner - Failed to run sync process.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: The key "Get a $100 AT&T Visa® Reward Card because you’re ordering TV" does not have the correct format. Key and container need to match [-_~.a-zA-Z0-9]+.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.sphere.sdk.utils.CompletableFutureUtils.lambda$transferResult$0(CompletableFutureUtils.java:84)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: The key "Get a $100 AT&T Visa® Reward Card because you’re ordering TV" does not have the correct format. Key and container need to match [-_~.a-zA-Z0-9]+.
        at io.sphere.sdk.customobjects.CustomObjectImpl.validatedKey(CustomObjectImpl.java:44)
        at io.sphere.sdk.customobjects.CustomObject.validatedKey(CustomObject.java:210)
        at io.sphere.sdk.customobjects.CustomObjectDraft.<init>(CustomObjectDraft.java:52)
        at io.sphere.sdk.customobjects.CustomObjectDraft.ofUnversionedUpsert(CustomObjectDraft.java:134)
        at com.commercetools.sync.services.impl.UnresolvedReferencesServiceImpl.save(UnresolvedReferencesServiceImpl.java:65)
        at com.commercetools.sync.products.ProductSync.keepTrackOfMissingReferences(ProductSync.java:237)
        at com.commercetools.sync.products.ProductSync.lambda$syncOrKeepTrack$4(ProductSync.java:206)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
        at com.commercetools.sync.products.ProductSync.syncOrKeepTrack(ProductSync.java:212)
        at com.commercetools.sync.products.ProductSync.lambda$syncBatch$3(ProductSync.java:179)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        ... 8 more

**Expected behavior**
The custom object is created with the key of the product either: stripped of invalid chars, or replacing them with appropriate ones.

**Comment by heshamMassoud** [comment]
Hi @svaj thanks for opening the issue. I can see how this could happen. It is unfortunate that keys are not validated consistently across endpoints. Nevertheless, we will provide a fix for it asap.

**Comment by heshamMassoud** [comment]
In the mean time, is using a different key for products an option? Because the key `Get a $100 Visa® Reward Card because you’re ordering TV` seems to be more like a description sentence and not a very typical unique identifier.

**Comment by heshamMassoud** [comment]
@svaj The problem here with stripping invalid chars is that if you have 2 products with those keys:

`Visa®` and `Visa©`

If the library strips the invalid chars away, both products will (from the POV of the library) have the same key `Visa`. And this would be unexpected for the user since he/she provided 2 different keys initially. 

Which leaves us with 3 solutions:
 either to 
1. Replace each invalid char with a unique invalid char. One way to do this would be to encode all chars with their unicode equivalent and decode when processing but the downside here would be that the keys would be human-readable anymore on the platform. 

2. Not allow syncing any products with keys that don't match the [`CustomObject` key regex from CTP.](https://docs.commercetools.com/http-api-projects-custom-objects#customobject)

3. Ask to remove the validation on CustomObjects keys on CTP.

In my opinion, **1** is a no-go. I am more for **2** until eventually (maybe) **3** also happens. 

What do you think? Do you have other ideas?

**Comment by heshamMassoud** [comment]
Hi @svaj, we decided to go with hashing the keys before storing them as custom objects. The is already merged to master. 

Will be released on Tuesday.

**Comment by heshamMassoud** [comment]
This is now released in [`1.7.0`](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#170----jan-7-2020)
